- name: This creates a directory
  tags: directory
  file:
      path: /var/www/website/
      state: directory
      owner: root
      group: root
      mode: u+rwx,g+rwx,o+rwx

- name: This unzip directory
  tags: directory
  unarchive:
      src: https://www.free-css.com/assets/files/free-css-templates/download/page296/finexo.zip
      dest: /var/www/website/
      remote_src: yes

- name: This copies content
  tags: nginx
  copy:
      src: ~/ansibledemo/demo
      dest: /etc/nginx/sites-available/
   
- name: This removes the old default config from sites enable
  tags: nginx
  file:
      path: /etc/nginx/sites-enabled/default
      state: absent
   
- name: This enables the new demo configuaion file options
  tags: nginx
  file:
      src: /etc/nginx/sites-available/demo
      dest: /etc/nginx/sites-enabled/demo
      state: link
      owner: root
      group: root


- name: This reloads the nginx confiuration
  tags: nginx
  service:
      name: nginx
      state: reloaded


- name: This restarts the nginx service
  tags: nginx
  service:
      name: nginx
      state: started
      enabled: yes

- name: allow UFW service
  tags: nginx
  ufw:
      rule: allow
      name: OpenSSH

- name: allow the Full Nginx service
  tags: nginx
  ufw:
      rule: allow
      name: Nginx Full 

- name: enable the ufw service
  tags: nginx
  ufw:
      state: enabled
      policy: allow
